#Modifiez ce makefile avec les règles standart d'Epitech : all, clean, fclean, re
#Gardez le nom et les SRCS déjà indiquées
#Le makefile ne doit rien afficher durant aucune de ses commandes, excepté en cas d'erreur
#exemple d'erreur : Faire deux fois Make d'affilé

NAME	= program

SRCS	= ./all.c \
	  ./clean.c \
	  ./fclean.c \
	  ./re.c
