#Modifiez ce makefile avec les règles standart d'Epitech : all, clean, fclean, re
#Faites en sorte que le makefile s'actualise dès que vous modifiez header.h
#Exemple : Faites make, modifiez le header, refaite make, le programme doit recompiler

NAME	= program

SRCS	= ./main.c
