#!/bin/sh

make &>/dev/null
if ./program ; then
    echo "Test 1 'make' successfull"
else
    echo "Test 1 'make' failed"
    exit 1
fi

echo "#ifndef HEADER_H_
    #define HEADER_H_

    #include <stdio.h>
    #include <stdio.h>

#endif
" > header.h

test=`make`
make="make: Nothing to be done for 'all'."

if [ "$test" != "$make" ]; then
    echo "Test 2 'make' successfull"
else
    echo "Test 2 'make' failed"
    echo "#ifndef HEADER_H_
        #define HEADER_H_

        #include <stdio.h>

    #endif
    " > header.h
    exit 1
fi

echo "#ifndef HEADER_H_
    #define HEADER_H_

    #include <stdio.h>

#endif
" > header.h
