#!/bin/sh

make &>/dev/null
if ./program ; then
    echo "Test 1 'make' successfull"
else
    echo "Test 1 'make' failed"
    exit 1
fi

make re &>/dev/null
if ./program ; then
    echo "Test 2 'make re' successfull"
else
    echo "Test 2 'make re' failed"
    exit 2
fi

make clean &>/dev/null
if find *.o &>/dev/null ; then
    echo "Test 3 'make clean' failed"
    exit 3
else
    echo "Test 3 'make clean' successfull"
fi

make fclean &>/dev/null
if find program &>/dev/null ; then
    echo "Test 4 'make fclean' failed"
    exit 4
else
    echo "Test 4 'make fclean' successfull"
fi

echo "Exercice 2 done"
