#Modifiez ce makefile avec les règles standart d'Epitech : all, clean, fclean, re
#Gardez le nom et les SRCS déjà indiquées
#Si la variable VAR est égale à 1, compilez normalement. Sinon, affichez un message d'erreur avec print ou echo
#Une fois ceci fait, si le fichier est re ou all, affichez le nom du fichier en bleu à la compilation. Sinon, affichez le nom en rouge
#Pas de script de test pour celui-là

VAR		= 1

NAME	= program

SRCS	= ./all.c \
	  ./clean.c \
	  ./fclean.c \
	  ./re.c
