#Appelez les makefiles des dossiers Project1 et Project2 et copiez les éxecutables à la racine
#Faites une règle fclean qui supprime les éxécutables de ce dossier puis appellent le fclean des makefiles de Project1 et Project2
