#Modifiez ce makefile avec les règles standart d'Epitech : all, clean, fclean, re
#Compilez ce programme en écrivant le chemin total une seule fois
#Pas de script de test pour celui-là

NAME	= program
