#!/bin/sh

test= make
if [ -z $test ]
then
    echo "test"
else
    echo $test
fi


test= make
if [ -z $test ] ; then
    echo "Test 1 'make' successfull"
else
    echo "Test 1 'make' failed"
    echo "What was showed:"
    echo test
    exit 1
fi

test= make re
if [ -z $test ] ; then
    echo "Test 2 'make re' successfull"
else
    echo "Test 2 'make re' failed"
    echo "What was showed:"
    echo test
    exit 1
fi

test= make clean
if [ -z $test ] ; then
    echo "Test 3 'make clean' successfull"
else
    echo "Test 3 'make clean' failed"
    echo "What was showed:"
    echo test
    exit 1
fi

test= make fclean
if [ -z $test ] ; then
    echo "Test 4 'make fclean' successfull"
else
    echo "Test 4 'make fclean' failed"
    echo "What was showed:"
    echo test
    exit 1
fi
