#Modifiez ce makefile avec les règles standart d'Epitech : all, clean, fclean, re
#Gardez le nom et les SRCS déjà indiquées
#Faites en sorte que le makefile rajoute un message pour chaque .c compilé en .o
#Ensuite, faites en sorte que le makefile affiche [*.c] -> [*.o] à chaque point c compilé, * étant le nom du fichier
#Exemple: [test.c] -> [test.o]
#Pas de script de test pour celui-là

NAME	= program

SRCS	= ./all.c \
	  ./clean.c \
	  ./fclean.c \
	  ./re.c
