#!/bin/sh

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

# make all

count=`grep -o -i CFLAGS Makefile | wc -l 2>/dev/null`

make > /dev/null
if ./a.out ; then
    echo "make all:${green}OK${reset}"
else
    echo "make all:${red}KO${reset}"
    exit 1
fi

# make re

echo "#ifndef HEADER_H_
    #define HEADER_H_

    #include <stdio.h>
    #include <stdio.h>

#endif
" > header.h

test=`make`
make="make: Nothing to be done for 'all'."

if [ "$test" != "$make" ]; then
    echo "make after header modification:${green}OK${reset}"
else
    echo "make after header modification:${red}KO${reset}"
    echo "#ifndef HEADER_H_
        #define HEADER_H_

        #include <stdio.h>

    #endif
    " > header.h
    exit 2
fi

echo "#ifndef HEADER_H_
    #define HEADER_H_

    #include <stdio.h>

#endif
" > header.h

make re > /dev/null
if ./a.out ; then
    echo "make re:${green}OK${reset}"
else
    echo "make re:${red}KO${reset}"
    exit 3
fi

#make clean

make clean > /dev/null
count=`find -name "*.o" 2>/dev/null | wc -l`
if [ $count != 0 ]
then
    echo "make clean:${red}KO${reset}"
    exit 4
else
    echo "make clean:${green}OK${reset}"
fi

#make fclean

make fclean > /dev/null
if [ ! -f "a.out" ]
then
    echo "make fclean:${green}OK${reset}"
else
    echo "make fclean:${red}KO${reset}"
    exit 5
fi
