#Modifiez ce makefile avec les règles standart d'Epitech : all, clean, fclean, re
#utilisez la variable CFLAGS dans votre makefile, mais ne l'intégrez pas dans votre compilation
#Une fois fait, renseignez vous sur les autres variables implicites
#Pas de test pour cet exercice

NAME	= program

SRCS	= ./main.c
